apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testsreact-test-app-rhtap-consoledot-frontend-build
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testsreact-test-app-rhtap-consoledot-frontend-build
    app.kubernetes.io/part-of: rhtap-consoledot-frontend-build
  name: testsreact-test-app-rhtap-consoledot-frontend-build
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: testsreact-test-app-rhtap-consoledot-frontend-build
status:
  loadBalancer: {}
